### ISSUE TITLE
Ontology WASM public code-review/auditing

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology#781]
Ontology WASM (branch code-audit-preview) is under public code-review and auditing.

This issue is to track the auditing progress.

**Comment by ghost** [comment]
@Honglei-Cong , could you please add a one-liner comment, thus external folks can understand what this issue is about?

**Comment by Honglei-Cong** [comment]
OK

**Comment by laizy** [comment]
The first audit was started in March, which focusing on the `ontology/vm/wasm` module, and we found some fundamental technical issues, so we reverted and re-implemented it. Now the second audit has been started, which focusing on the `wagon` lib. And we will constantly update the audit report here.

ontology:
- [x] determine the wasm contract gas fee 
- [x] limit the wasm contract size, currently 512k is enough for most usecase
- [x] limit the table size to avoid memory attack
- [x] avoid memory allocation attack in some runtime host function(#1046)
- [x] contract need pass the validation before deploy (#1047)
- [x] add prefix `ontio_` to current runtime api 
- [x] add `sha256`, ~~`sha3`~~ api

ontio/wagon:
- [x] check `offset` in element section 
- [x] add call depth limitation ([pr-10](https://github.com/ontio/wagon/pull/10))
- [x] add validation from rust libs(https://github.com/ontio/wagon/pull/13)

go-interpreter/wagon:
- [x] fix infinite recursion in DuplicateExportError.Error (pr-146)
- [x] fix memory allocation attack ([pr-148](https://github.com/go-interpreter/wagon/pull/148))
- [x] function DecodeModule implementation is not consistent with the wasm specification ([issue-144](https://github.com/go-interpreter/wagon/issues/144))
- [x] type validation of polymorphic opcode is not consistent with the wasm specification([issue-143](https://github.com/go-interpreter/wagon/issues/143))
- [x] names used in wasm import/export/module etc need to be valid utf-8 string ([issue-145](https://github.com/go-interpreter/wagon/issues/145))
- [x] fix leb128 decoding
